### PR TITLE
feat: add option to fill video to screen

### PR DESCRIPTION
**Pull request by stickyburn**
Based on #51 , this PR adds an option to enable 'fill to screen'. If enabled, the video is filled when maximized.

image

### CODE REVIEW

**Review by lamarios — APPROVED** [review]
Thanks for the PR, code looks good. I'll have to test it on my own before merging.

**Comment by lamarios** [comment]
I had a look while it does what it says, wouldn't it be better if it is on a video basis ? with like a pinch gesture when the video is playing full screen ?

**Comment by lamarios** [comment]
I did some tests on the video player library to implement it (as i keep my own fork) and it won't be easy as it looks like changing the fit of the video doesn't update live on a full screen video  (unless i go back and forth from and to full screen). I'll need to dig deeper on this.

**Comment by stickyburn** [comment]
> I had a look while it does what it says, wouldn't it be better if it is on a video basis ? with like a pinch gesture when the video is playing full screen ?

This is what I initially desired but would require some pointers on. Do we merge this or come back to it later?

**Comment by lamarios** [comment]
> > I had a look while it does what it says, wouldn't it be better if it is on a video basis ? with like a pinch gesture when the video is playing full screen ?
> 
> This is what I initially desired but would require some pointers on. Do we merge this or come back to it later?

This is a bit more involved. I"m actually using an abandoned library for the video player that i forked and keep afloat. The changes would need to be there because once in full screen it doesn't respond to gestures if implemented in the application itself.

I want to rewrite the player to use the base video_player library but that will require a lot of work to reach feature parity

**Comment by stickyburn** [comment]
I understand. I think it's nice to have atleast this option for now. Wdyt?

**Comment by lamarios** [comment]
sure, let's merge it

**Pull request merged**
