### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As promised, here's my "Fastlane Starter Pack" for your [F-Droid inclusion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12912) (the part the bot complained about). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this (e.g. add per-release changelogs), or to replace screenshots etc, update descriptions… All in your hands now. F-Droid as well as my repo's updater will fetch your changes with their corresponding releases then. Because, who would know better than you what needs to be in the descriptions, changelogs and so on? :smiley:

### CODE REVIEW

**Comment by lamarios** [comment]
Thanks for the PR, the metadata is actually already in the /android folder because it is how it works with flutter.  I'll probably change its location instead and set the path manually in my fastlane parameters.

Also I don't think I want to mention youtube in the descriptions as it is what is sent to google play as well.

**Comment by lamarios** [comment]
I hope fdroid handles symlinks :)

**Comment by IzzySoft** [comment]
> metadata is actually already in the /android folder

Ah, so F-Droid missed it (as did I for my repo). That's not one of the "standard locations".

> Also I don't think I want to mention youtube in the descriptions as it is what is sent to google play as well.

Good point.

> I hope fdroid handles symlinks :)

As far as I know it does. My repo does not (yet), but I can instead explicitly define where to look for it (which F-Droid does not). So I'll do that now, pointing to your "hidden" Fastlane structure.

Hm, nothing in the `/android` folder. Looks like you already moved it to `/fastlane` :smile: If you accept some suggestions:

* maybe removing the empty `video.txt`? Doesn't hurt, though.
* `full_description.txt` shouldn't be just a copy of `short_description.txt` but have some "real description" :wink:
* would it be possible for the changelogs to have files specific to the releases (`<versionCode>.txt`)?
* shall I replace the screenshots I have here with yours then? I have some more in my repo (looking like they might have come from an earlier PlayStore-Listing). I'll set my end now to copy from yours, so if you think those shall be kept, you have them in this PR.

If you think everything is ready, it's of course fine to simply close my PR here. Or cherry-pick if you want some pieces :wink:

**Comment by lamarios** [comment]
It actually looks like fdroid didn't handle symlink. So I did the opposite, move my fast lane folder to root then synlibk in android folder and it looks like it's working.

I'm hindsight I could just do with the fast lane in root as i don't build using fast lane.

I'll close this issue. The fdroid pr is up to date with my last release.

**Comment by lamarios** [comment]
I'll update the long description later in the meta data.

**Comment by lamarios** [comment]
Done

**Comment by IzzySoft** [comment]
> I'll update the long description later in the meta data.

1. please ping me when done so I set it in my repo
2. we cannot merge at F-Droid before it's there, as Fastlane will be taken from the very same commit as the build is done from (so we will need to "shift" the commit once more when everything is in place).

**Comment by lamarios** [comment]
Yep all done.

**Comment by IzzySoft** [comment]
Thanks! Just a hint: If you later check in the app and see a bunch of unexpected empty lines, that's because F-Droid replaces all `\n` by `<br>`. To work around that nasty behavior it helps to keep all HTML in a single line. For my repo, my framework takes care for that; if you wish I can provide you the corresponding code snippet. Or you use this 
[full_description.pl.txt](https://github.com/lamarios/clipious/files/11303975/full_description.pl.txt) (after removing the `.txt` which I had to add or Github wouldn't allow me to attach it here) to generate the `full_description.txt` via CI on each release.

**Comment by lamarios** [comment]
ok, i did it manually. it's not like it's going to change very often anyway. Should be good to go now

**Pull request closed without merging**
